### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by sojusnik** [Xunius/tagextract#1]
Getting the following error message, when launching from terminal:

```
xxx@yyy:~$ python /home/sojusnik/Downloads/tagextract-master/tagextract.py -z /home/sojusnik/Mitschrift.txt buch
# <readFile>: Open input file:
/home/sojusnik/Mitschrift.txt

# <readFile>: Reading lines...
Traceback (most recent call last):
  File "/home/sojusnik/Downloads/tagextract-master/tagextract.py", line 262, in <module>
    main(FILEIN,FILEOUT,TAG,SYNTAX,args.verbose)
  File "/home/sojusnik/Downloads/tagextract-master/tagextract.py", line 206, in main
    text=tools.readFile(filein,verbose)
  File "/home/sojusnik/Downloads/tagextract-master/lib/tools.py", line 32, in readFile
    lines=u''.join(lines)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
```

Seems to be related to this [one](http://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte).

Observed under Ubuntu 15.10.

**Comment by Xunius** [comment]
Thanks for pointing it out. I've made a fix which hopefully solves the issue

**Comment by sojusnik** [comment]
Your recent commits seem to solve the unicode issue, but I'm getting a new one:

```
~$ python /home/sojusnik/Downloads/tagextract-master/tagextract.py -z /home/sojusnik/Mitschrift.txt buch

# <readFile>: Open input file:
/home/sojusnik/Mitschrift.txt

# <readFile>: Reading lines...
# <readFile>: Got all data.
# <tagextract>: Extracting tagged lines...
Traceback (most recent call last):
  File "/home/sojusnik/Downloads/tagextract-master/tagextract.py", line 262, in <module>
    main(FILEIN,FILEOUT,TAG,SYNTAX,args.verbose)
  File "/home/sojusnik/Downloads/tagextract-master/tagextract.py", line 210, in main
    newtext=tagfinder.extractTag(text,tag)
  File "/home/sojusnik/Downloads/tagextract-master/tagextract.py", line 174, in extractTag
    for ii in tagdict[tag]:
KeyError: 'buch'
```

**Comment by Xunius** [comment]
The quick answer is add @ before your tag: @buch.

I'll make a better fix to relax this requirement in a short while.

**Comment by Xunius** [comment]
Thanks for reporting.
The error occurred because I assumed the user specific a tag by adding a @ symbol (e.g. @buch).
I've relaxed this requirement in the fix.

**Comment by sojusnik** [comment]
The new commit seems not to help:

```
~$ python /home/sojusnik/Downloads/tagextract-master/tagextract.py -z /home/sojusnik/Mitschrift.txt buch

# <readFile>: Open input file:
/home/sojusnik/Mitschrift.txt

# <readFile>: Reading lines...
# <readFile>: Got all data.
# <tagextract>: Extracting tagged lines...
Traceback (most recent call last):
  File "/home/sojusnik/Downloads/tagextract-master/tagextract.py", line 266, in <module>
    main(FILEIN,FILEOUT,TAG,SYNTAX,args.verbose)
  File "/home/sojusnik/Downloads/tagextract-master/tagextract.py", line 214, in main
    newtext=tagfinder.extractTag(text,tag)
  File "/home/sojusnik/Downloads/tagextract-master/tagextract.py", line 178, in extractTag
    for ii in tagdict[tag]:
KeyError: '@buch'
```

Also tried it with another tag, but getting even another error message:

```
~$ python /home/sojusnik/Downloads/tagextract-master/tagextract.py -z /home/sojusnik/Mitschrift.txt machen

# <readFile>: Open input file:
/home/sojusnik/Mitschrift.txt

# <readFile>: Reading lines...
# <readFile>: Got all data.
# <tagextract>: Extracting tagged lines...
Traceback (most recent call last):
  File "/home/sojusnik/Downloads/tagextract-master/tagextract.py", line 266, in <module>
    main(FILEIN,FILEOUT,TAG,SYNTAX,args.verbose)
  File "/home/sojusnik/Downloads/tagextract-master/tagextract.py", line 214, in main
    newtext=tagfinder.extractTag(text,tag)
  File "/home/sojusnik/Downloads/tagextract-master/tagextract.py", line 194, in extractTag
    result_lines=u''.join(result_lines)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
```

**Comment by Xunius** [comment]
Could you paste a few lines containing the tag (@buch and @machen) in your file? Do both of them (buch and machen) have a @ right before them?
In your 2nd try (searching for machen), it seems to have found something, but failed again at the unicode issue which is my bad. Could you try commenting out this line at 163: `text=text.encode('utf8')` and try again. I believe that line is causing the problem.

One possible reason is the tag @buch is followed by a space.
The regex I'm using assumes @tag is followed by one of the following: `,`, `;`, `@`, newline or end of string. Because in my own usage cases I have some tags that are two words, e.g. 'math equations'. So I didn't include spaces in the regex. This might not be a good idea because you have to remember to append a comma or so.

**Comment by Xunius** [comment]
I've added spaces as tag definition delimiters. Please try again and see if it works.

**Comment by sojusnik** [comment]
Commenting line 163 out did indeed help!

But I'm getting very weird results, even with your recent "spaces" commit. Just try to extract all the tags, one by one, from my Zim Wiki file:

> ====== TagExtract ======
> @tagwithnotext
> 
> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. @tagattheend
> 
> Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. @tagattheend
> 
> [ ] what's the story morning glory? @tagwithtasks 
> 
> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. @tagattheend @tagafteratag
> 
> @tagbeforetext Nam liber tempor cum
> Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
> 
> @tagbeforetext Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
> 
> Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.

Ideally, tags that have no text around them, like @tagwithnotext shouldn't be extracted at all, since they mark a site, and not a specific text within a site.

Tags at the end of a sentence should extract the whole paragraph before them, like @tagattheend, and tags before a sentence, @tagbeforetext, should extract the whole paragraph, that comes after the tag.

@tagafteratag and @tagwithtasks were created to see, if extracting also works with checkboxes and when a tag is before a tag.

BTW, Zim Wiki doesn't allow to create tags with multiple words connected with a space, only with an underscore.

Do you think, that this is achievable?

Many thanks in advance!

**Comment by Xunius** [comment]
Thank god we finally solved all technical mistakes. 
In terms of the results, they are weird but they worked as expected, the problem is we are expecting different results. As I mentioned in the readme this is largely an experimental thing to implement in-text tagging rather than note-level tagging. And this is just one of many possible ways of doing this and probably not the best way of doing it. I think your interpretations also make good sense.

I developed this having a few vague thoughts in mind. When one is taking a note, he may be spending a few paragraphs around a single topic. Later on to mark all these paragraphs with a tag, he could put a tag at the end of each. But to save some effort, I allow putting one tag at the end of the last paragraph and indent it by 1 tab, thus marking all previous paragraphs that have 1 tab-level higher. 

 To explain the main topic more specifically, he may take some more notes on a few sub-topics, again by indenting each sub-topic by a tab wrt to the main text. In each sub-topic, he may plant one or more tags that are specific to the sub-topic itself. Later on, he could retrieve these sub-topics by using sub-level tags, or retrieve everything related to the main topic, including all sub-topics, by searching for the main tag. The idea is to extract a tag and its context, with different levels of contexts.  

I may have confused you. Again that is one possible way and your ideas make sense too. The @tagattheend and @tagbeforetext can be achieved, I believe, but I think if one decides to decorate the paragraph with multiple tags (interpreting it from different perspectives for instance), this may make the texts not so good-looking. Again if a few paragraphs are talking about the same thing, you need to copy these tags to each of them. I didn't use checkboxes in zim myself so I don't know too much about how the texts look.

So, thanks for your interests and patience, and I suggest have a quick look at the readme. If you have some good suggestions on this in-text tagging method (pen-and-paper probably works way better in such cases), let me know and I will see if I could make another design that suits your needs.

**Comment by Xunius** [comment]
I've made a quick implement of your design. check out the branch at https://github.com/Xunius/tagextract/tree/tagextract-sojusnik
use `python tagextract-sojusnik path_to_input_file @tag`. I assume you use zim mostly so I removed the selection of -m or -z. You can easily bring that option back if you need.

**Comment by sojusnik** [comment]
Thanks! At a first glance it seems to work very well. I'll give you more feedback after some testing.

Best wishes!
